// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: reply/api/api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReplyServer_Ping_FullMethodName           = "/ReplyServer/Ping"
	ReplyServer_ReplyByGroupID_FullMethodName = "/ReplyServer/ReplyByGroupID"
)

// ReplyServerClient is the client API for ReplyServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReplyServerClient interface {
	Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingRes, error)
	ReplyByGroupID(ctx context.Context, in *ReplyByGroupIDReq, opts ...grpc.CallOption) (*ReplyByGroupIDRes, error)
}

type replyServerClient struct {
	cc grpc.ClientConnInterface
}

func NewReplyServerClient(cc grpc.ClientConnInterface) ReplyServerClient {
	return &replyServerClient{cc}
}

func (c *replyServerClient) Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingRes)
	err := c.cc.Invoke(ctx, ReplyServer_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replyServerClient) ReplyByGroupID(ctx context.Context, in *ReplyByGroupIDReq, opts ...grpc.CallOption) (*ReplyByGroupIDRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplyByGroupIDRes)
	err := c.cc.Invoke(ctx, ReplyServer_ReplyByGroupID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReplyServerServer is the server API for ReplyServer service.
// All implementations must embed UnimplementedReplyServerServer
// for forward compatibility.
type ReplyServerServer interface {
	Ping(context.Context, *PingReq) (*PingRes, error)
	ReplyByGroupID(context.Context, *ReplyByGroupIDReq) (*ReplyByGroupIDRes, error)
	mustEmbedUnimplementedReplyServerServer()
}

// UnimplementedReplyServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReplyServerServer struct{}

func (UnimplementedReplyServerServer) Ping(context.Context, *PingReq) (*PingRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedReplyServerServer) ReplyByGroupID(context.Context, *ReplyByGroupIDReq) (*ReplyByGroupIDRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplyByGroupID not implemented")
}
func (UnimplementedReplyServerServer) mustEmbedUnimplementedReplyServerServer() {}
func (UnimplementedReplyServerServer) testEmbeddedByValue()                     {}

// UnsafeReplyServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReplyServerServer will
// result in compilation errors.
type UnsafeReplyServerServer interface {
	mustEmbedUnimplementedReplyServerServer()
}

func RegisterReplyServerServer(s grpc.ServiceRegistrar, srv ReplyServerServer) {
	// If the following call pancis, it indicates UnimplementedReplyServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReplyServer_ServiceDesc, srv)
}

func _ReplyServer_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplyServerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplyServer_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplyServerServer).Ping(ctx, req.(*PingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplyServer_ReplyByGroupID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplyByGroupIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplyServerServer).ReplyByGroupID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplyServer_ReplyByGroupID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplyServerServer).ReplyByGroupID(ctx, req.(*ReplyByGroupIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ReplyServer_ServiceDesc is the grpc.ServiceDesc for ReplyServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReplyServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ReplyServer",
	HandlerType: (*ReplyServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ReplyServer_Ping_Handler,
		},
		{
			MethodName: "ReplyByGroupID",
			Handler:    _ReplyServer_ReplyByGroupID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reply/api/api.proto",
}
