// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: danmaku_reply/api/embedding.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_danmaku_reply_api_embedding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_danmaku_reply_api_embedding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_danmaku_reply_api_embedding_proto_rawDescGZIP(), []int{0}
}

// 请求结构：包含一句话
type EmbeddingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingRequest) Reset() {
	*x = EmbeddingRequest{}
	mi := &file_danmaku_reply_api_embedding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingRequest) ProtoMessage() {}

func (x *EmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_danmaku_reply_api_embedding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingRequest.ProtoReflect.Descriptor instead.
func (*EmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_danmaku_reply_api_embedding_proto_rawDescGZIP(), []int{1}
}

func (x *EmbeddingRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// 返回结构：embedding 是 float 向量
type EmbeddingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embedding     []float64              `protobuf:"fixed64,1,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingResponse) Reset() {
	*x = EmbeddingResponse{}
	mi := &file_danmaku_reply_api_embedding_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingResponse) ProtoMessage() {}

func (x *EmbeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_danmaku_reply_api_embedding_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingResponse.ProtoReflect.Descriptor instead.
func (*EmbeddingResponse) Descriptor() ([]byte, []int) {
	return file_danmaku_reply_api_embedding_proto_rawDescGZIP(), []int{2}
}

func (x *EmbeddingResponse) GetEmbedding() []float64 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

var File_danmaku_reply_api_embedding_proto protoreflect.FileDescriptor

const file_danmaku_reply_api_embedding_proto_rawDesc = "" +
	"\n" +
	"!danmaku_reply/api/embedding.proto\x12\tembedding\"\a\n" +
	"\x05Empty\"&\n" +
	"\x10EmbeddingRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"1\n" +
	"\x11EmbeddingResponse\x12\x1c\n" +
	"\tembedding\x18\x01 \x03(\x01R\tembedding2\x89\x01\n" +
	"\x10EmbeddingService\x12I\n" +
	"\fGetEmbedding\x12\x1b.embedding.EmbeddingRequest\x1a\x1c.embedding.EmbeddingResponse\x12*\n" +
	"\x04Ping\x12\x10.embedding.Empty\x1a\x10.embedding.EmptyB\x13Z\x11danmaku_reply/apib\x06proto3"

var (
	file_danmaku_reply_api_embedding_proto_rawDescOnce sync.Once
	file_danmaku_reply_api_embedding_proto_rawDescData []byte
)

func file_danmaku_reply_api_embedding_proto_rawDescGZIP() []byte {
	file_danmaku_reply_api_embedding_proto_rawDescOnce.Do(func() {
		file_danmaku_reply_api_embedding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_danmaku_reply_api_embedding_proto_rawDesc), len(file_danmaku_reply_api_embedding_proto_rawDesc)))
	})
	return file_danmaku_reply_api_embedding_proto_rawDescData
}

var file_danmaku_reply_api_embedding_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_danmaku_reply_api_embedding_proto_goTypes = []any{
	(*Empty)(nil),             // 0: embedding.Empty
	(*EmbeddingRequest)(nil),  // 1: embedding.EmbeddingRequest
	(*EmbeddingResponse)(nil), // 2: embedding.EmbeddingResponse
}
var file_danmaku_reply_api_embedding_proto_depIdxs = []int32{
	1, // 0: embedding.EmbeddingService.GetEmbedding:input_type -> embedding.EmbeddingRequest
	0, // 1: embedding.EmbeddingService.Ping:input_type -> embedding.Empty
	2, // 2: embedding.EmbeddingService.GetEmbedding:output_type -> embedding.EmbeddingResponse
	0, // 3: embedding.EmbeddingService.Ping:output_type -> embedding.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_danmaku_reply_api_embedding_proto_init() }
func file_danmaku_reply_api_embedding_proto_init() {
	if File_danmaku_reply_api_embedding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_danmaku_reply_api_embedding_proto_rawDesc), len(file_danmaku_reply_api_embedding_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_danmaku_reply_api_embedding_proto_goTypes,
		DependencyIndexes: file_danmaku_reply_api_embedding_proto_depIdxs,
		MessageInfos:      file_danmaku_reply_api_embedding_proto_msgTypes,
	}.Build()
	File_danmaku_reply_api_embedding_proto = out.File
	file_danmaku_reply_api_embedding_proto_goTypes = nil
	file_danmaku_reply_api_embedding_proto_depIdxs = nil
}
